name: Build Android Production APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "ATUALIZACOES.md"

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: production
