name: Publish OTA Update

on:
  push:
    branches:
      - main

jobs:
  update:
    name: OTA Update Production
    type: update
    params:
      branch: production
      message: Atualização automática via workflow
