name: Publish OTA Update

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "App.js"
      - "package.json"

jobs:
  update:
    name: OTA Update Production
    type: update
    params:
      branch: production
      message: "Atualização automática via workflow"
